### ISSUE TITLE
Error while adding [NAME].exe to glue

### ISSUE THREAD

**Issue by r2fo** [hawksh/Hidden-miner-builder#7]
.

**Comment by hawksh** [comment]
> 
> 
> Hi I get this error even when reopening your program. I'm using a vm because I have a Mac

Hello!
I checked there are no errors. I need more information, maybe a log from the "logs" folder. Or contact me by telegram. This is when working with the gluing function in the builder.
But then you write about the launch. If this happens when the builder starts, then it is possible that it is due to the VM. To protect the builder, protectors are used that may not work correctly with some VMs.
